# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MDC-Playground' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MDC-Playground
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/HeaderStackView'
  pod 'MaterialComponents/NavigationBar'
  pod 'MaterialComponents/OverlayWindow'
  pod 'MaterialComponents/FlexibleHeader'
  pod 'MaterialComponents/ShadowElevations'
  pod 'MaterialComponents/ShadowLayer'
  pod 'MaterialComponents/ProgressView'
  pod 'MaterialComponents/Typography'
end
